version: '3.4'

services:
  orderdb:
    container_name: orderdb
    hostname: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=OddsDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=admin@order.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    depends_on:
      - orderdb
    volumes:
      - pgadmin_data:/root/.pgadmin
     
  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OddsConnectionString=Server=orderdb;Port=5432;Database=OrderDb;User Id=admin;Password=admin1234;"
    depends_on:
      - orderdb
    ports:
      - "8000:80"
